name:             D.&thinsp;R. Driver
description:      "Describe the website."

# Author information
owner:
  name:           Daniel Driver
  avatar:         drd.png
  email:          mail@danieldriver.com
  twitter:        danieldriver
  github:         danieldriver
  # For Google Authorship see https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
links:
  - title: Home
    url: /
  - title: Notes
    url: /notes/
  - title: Childs
    url: /bsc/
  - title: About
    url: /about/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Toronto
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

#include: [".htaccess"]
#exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]